### ISSUE TITLE
Add Icon Badges to Documentation

### ISSUE THREAD

**Issue by wolfofdalalst** [wolfofdalalst/letterboxd-clone#1]
Update the documentation to include icon badges that display build status, version, license, and other relevant information. This will improve readability and provide quick insights into the project's status. Add badges in the main `README.md` file, and ensure they are appropriately linked and up-to-date.

**Comment by sayanjit082805** [comment]
Can you assign me this issue please?

**Comment by wolfofdalalst** [comment]
@sayanjit082805 assigned!
